name: "Default deployment"
stages:     
   network:
     - if: '[ ! -f "/run/cos/recovery_mode" ]'
       name: "Setup k3s"
       environment_file: "/etc/systemd/system/k3s-agent.service.env"
       systemctl:
         start: 
         - k3s-agent
     - commands:
       - |
            chmod 600 /etc/systemd/system/k3s-agent.service.env
       - ulimit -u unlimited
       - ulimit -n 900000
