name: Build sgnOS images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-fedora-amd64:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up elemental 
        uses: ludea/elemental-setup@v1.10
      - name: Build Fedora master-amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.fedora
          platforms: linux/amd64
          push: false
          load: true
          tags: sgnos_fedora_amd64_k3s:latest
          target: k3s-amd64
          build-args: |
            NODE=master
      - name: Build Fedora master amd64 iso
        run: sudo elemental build-iso sgnos_fedora_amd64_k3s:latest 
#docker run -v $PWD:/cOS -v /var/run:/var/run --entrypoint /usr/bin/luet-makeiso -i --rm quay.io/costoolkit/toolchain:0.8.7-16-gdcaac339 ./iso/master.yaml --image sgnos_fedora_amd64_k3s:latest --output sgnOS_fedora_amd64_k3s
      - uses: actions/upload-artifact@v2
        with:
          name: sgnOS_fedora_amd64_k3s.iso
          path: sgnOS_fedora_amd64_k3s.iso
          if-no-files-found: error

  build-ubuntu-amd64:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Build Ubuntu master-amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ubuntu
          platforms: linux/amd64
          push: false
          load: true
          tags: sgnos_ubuntu_amd64_k3s:latest
          target: k3s-amd64
          build-args: |
            NODE=master
      - name: Build Ubuntu amd64 iso
        run: docker run -v $PWD:/cOS -v /var/run:/var/run --entrypoint /usr/bin/luet-makeiso -i --rm quay.io/costoolkit/toolchain:0.8.7-16-gdcaac339 ./iso/master.yaml --image sgnos_ubuntu_amd64_k3s:latest --output sgnOS_ubuntu_amd64_k3s
      - uses: actions/upload-artifact@v2
        with:
          name: sgnOS_ubuntu_amd64_k3s.iso
          path: sgnOS_ubuntu_amd64_k3s.iso
          if-no-files-found: error

  build-alpine-amd64:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Build alpine amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.alpine
          platforms: linux/amd64
          push: false
          load: true
          tags: sgnos_alpine_amd64_k3s:latest
          build-args: |
            NODE=master
      - name: Build alpine amd64 iso
        run: docker run -v $PWD:/cOS -v /var/run:/var/run --entrypoint /usr/bin/luet-makeiso -i --rm quay.io/costoolkit/toolchain:0.8.7-16-gdcaac339 ./iso/master.yaml --image sgnos_alpine_amd64_k3s:latest --output sgnOS_alpine_amd64_k3s
      - uses: actions/upload-artifact@v2
        with:
          name: sgnOS_alpine_amd64_k3s.iso
          path: sgnOS_alpine_amd64_k3s.iso
          if-no-files-found: error

  build-fedora-arm64:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up elemental 
        uses: ludea/elemental-setup@v1.10
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build fedora aarch64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.fedora
          platforms: linux/arm64
          push: false
          load: true
          tags: sgnos_fedora_aarch64_k3s:latest
          target: base
          build-args: |
            NODE=master
      - name: Build Image
        id: build_image
        run: |
          sudo ./images/arm-img-builder.sh --model rpi64 --docker-image sgnos_fedora_aarch64_k3s:latest sgnOS_rpi64_fedora_k3s.img
      - uses: actions/upload-artifact@v2
        with:
          name: sgnOS_rpi64_k3s.img
          path: sgnOS_rpi64_k3s.img
          if-no-files-found: error

  build-ubuntu-arm64:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up elemental 
        uses: ludea/elemental-setup@v1.10
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Ubuntu aarch64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ubuntu
          platforms: linux/arm64
          push: false
          load: true
          tags: sgnos_ubuntu-aarch64_k3s-master:latest
          target: base
          build-args: |
            NODE=master
      - name: Build Image
        id: build_image
        run: |
          sudo ./images/arm-img-builder.sh --model rpi64 --docker-image sgnos_ubuntu-aarch64_k3s-master:latest sgnOS_ubuntu_rpi64_k3s-master.img
      - uses: actions/upload-artifact@v2
        with:
          name: sgnOS_ubuntu_rpi64_k3s-master.img
          path: sgnOS_ubuktu_rpi64_k3s-master.img
          if-no-files-found: error
