name: Build sgnOS images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-fedora-amd64:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up elemental 
        uses: ludea/elemental-setup@dev
      - name: Build Fedora master-amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.fedora
          platforms: linux/amd64
          push: false
          load: true
          tags: sgnos_fedora_amd64_k3s:latest
          target: k3s-amd64
      - name: Build Fedora master amd64 iso
        run: |
          sudo elemental build-iso --local sgnos_fedora_amd64_k3s:latest --output sgnOS_fedora_amd64_k3s.iso 
          ls
      - uses: actions/upload-artifact@v2
        with:
          name: sgnOS_fedora_amd64_k3s.iso
          path: sgnOS_fedora_amd64_k3s.iso
          if-no-files-found: error

  build-ubuntu-amd64:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up elemental 
        uses: ludea/elemental-setup@dev
      - name: Build Ubuntu master-amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ubuntu
          platforms: linux/amd64
          push: false
          load: true
          tags: sgnos_ubuntu_amd64_k3s:latest
          target: k3s-amd64
      - name: Build Ubuntu amd64 iso
        run: sudo elemental build-iso --local sgnos_ubuntu_amd64_k3s:latest --output sgnOS_ubuntu_amd64_k3s.iso
      - uses: actions/upload-artifact@v2
        with:
          name: sgnOS_ubuntu_amd64_k3s.iso
          path: sgnOS_ubuntu_amd64_k3s.iso
          if-no-files-found: error

  build-alpine-amd64:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up elemental 
        uses: ludea/elemental-setup@dev
      - name: Build alpine amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.alpine
          platforms: linux/amd64
          push: false
          load: true
          tags: sgnos_alpine_amd64_k3s:latest
      - name: Build alpine amd64 iso
        run: sudo elemental build-iso --local sgnos_alpine_amd64_k3s:latest --output sgnos_alpine_amd64_k3s.iso
      - uses: actions/upload-artifact@v2
        with:
          name: sgnos_alpine_amd64_k3s.iso
          path: sgnos_alpine_amd64_k3s.iso
          if-no-files-found: error

  build-fedora-arm64:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up elemental 
        uses: ludea/elemental-setup@dev
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build fedora aarch64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.fedora
          platforms: linux/arm64
          push: false
          load: true
          tags: sgnos_fedora_arm64_k3s:latest
          target: base
      - name: Build Image
        id: build_image
        run: sudo elemental build-iso --local -a arm64 sgnos_fedora_arm64_k3s:latest --output sgnos_fedora_arm64_k3s.iso
      - uses: actions/upload-artifact@v2
        with:
          name: sgnos_fedora_arm64_k3s.iso
          path: sgnos_fedora_arm64_k3s.iso
          if-no-files-found: error

  build-ubuntu-arm64:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up elemental 
        uses: ludea/elemental-setup@dev
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Ubuntu aarch64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ubuntu
          platforms: linux/arm64
          push: false
          load: true
          tags: sgnos_ubuntu_arm64_k3s:latest
          target: base
      - name: Build Image
        id: build_image
        run: sudo elemental build-iso --local -a arm64 sgnos_ubuntu_arm64_k3s:latest --output sgnos_ubuntu_arm64_k3s.iso
      - uses: actions/upload-artifact@v2
        with:
          name: sgnos_ubuntu_arm64_k3s.iso
          path: sgnos_ubuntu_arm64_k3s.iso
          if-no-files-found: error

  build-alpine-arm64:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up elemental 
        uses: ludea/elemental-setup@dev
      - name: Build alpine arm64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.alpine
          platforms: linux/arm64
          push: false
          load: true
          tags: sgnos_alpine_arm64_k3s:latest
      - name: Build alpine arm64 iso
        run: sudo elemental build-iso --local -a arm64 sgnos_alpine_arm64_k3s:latest --output sgnos_alpine_arm64_k3s.iso
      - uses: actions/upload-artifact@v2
        with:
          name: sgnos_alpine_arm64_k3s.iso
          path: sgnos_alpine_arm64_k3s.iso
          if-no-files-found: error
