name: Build sgnOS image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build-blue:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build master-amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: sgnos_amd64_k3s-master
          build-args: |
            NODE=master
      - name: Build master amd64 iso
        run: docker run -v $PWD:/cOS -v /var/run:/var/run --entrypoint /usr/bin/luet-makeiso --rm quay.io/costoolkit/toolchain ./iso/${NODE}.yaml --image sgnos_amd64_k3s-master
      - name: Build agent-amd64 🔧
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: sgnos_amd64_k3s-agent
          target: agent-amd64 
      - name: Build agent iso
        run: docker run -v $PWD:/cOS -v /var/run:/var/run --entrypoint /usr/bin/luet-makeiso --rm quay.io/costoolkit/toolchain ./iso/${NODE}.yaml --image sgnos_amd64_k3s-agent
      - name: Build master-aarch64
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          push: false
          tags: sgnos_aarch64_k3s-master
          target: master-aarch64
      - name: Build master aarch64 iso
        run: docker run -v $PWD:/cOS -v /var/run:/var/run --entrypoint /usr/bin/luet-makeiso --rm quay.io/costoolkit/toolchain ./iso/${NODE}.yaml --image sgnos_aarch64_k3s-master
      - name: Build agent-aarch64 🔧
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          push: false
          tags: sgnos_aarch64_k3s-agent
          target: agent-aarch64 
      - name: Build agent-aarch64 iso
        run: docker run -v $PWD:/cOS -v /var/run:/var/run --entrypoint /usr/bin/luet-makeiso --rm quay.io/costoolkit/toolchain ./iso/{NODE}.yaml --image sgnos_aarch64_k3s-agent

 
