name: Build sgnOS images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-fedora_amd64-master:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up elemental 
        uses: ludea/elemental-setup@v1.4
      - name: Build master-amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.fedora
          platforms: linux/amd64
          push: false
          load: true
          tags: sgnos_fedora_amd64_k3s-master:latest
          target: k3s-amd64
          build-args: |
            NODE=master
      - name: Build master amd64 iso
        run: docker run -v $PWD:/cOS -v /var/run:/var/run --entrypoint /usr/bin/luet-makeiso -i --rm quay.io/costoolkit/toolchain:0.8.7-16-gdcaac339 ./iso/master.yaml --image sgnos_fedora_amd64_k3s-master:latest --output sgnOS_fedora_amd64_k3s-master
      - uses: actions/upload-artifact@v2
        with:
          name: sgnOS_fedora_amd64_k3s-master.iso
          path: sgnOS_fedora_amd64_k3s-master.iso
          if-no-files-found: error

  build-ubuntu_amd64-master:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build master-amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ubuntu
          platforms: linux/amd64
          push: false
          load: true
          tags: sgnos_ubuntu_amd64_k3s-master:latest
          target: k3s-amd64
          build-args: |
            NODE=master
      - name: Build master amd64 iso
        run: docker run -v $PWD:/cOS -v /var/run:/var/run --entrypoint /usr/bin/luet-makeiso -i --rm quay.io/costoolkit/toolchain:0.8.7-16-gdcaac339 ./iso/master.yaml --image sgnos_ubuntu_amd64_k3s-master:latest --output sgnOS_ubuntu_amd64_k3s-master
      - uses: actions/upload-artifact@v2
        with:
          name: sgnOS_ubuntu_amd64_k3s-master.iso
          path: sgnOS_ubuntu_amd64_k3s-master.iso
          if-no-files-found: error

  build-alpine-amd64-master:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build master-amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.alpine
          platforms: linux/amd64
          push: false
          load: true
          tags: sgnos_alpine_amd64_k3s-master:latest
          build-args: |
            NODE=master
      - name: Build master amd64 iso
        run: docker run -v $PWD:/cOS -v /var/run:/var/run --entrypoint /usr/bin/luet-makeiso -i --rm quay.io/costoolkit/toolchain:0.8.7-16-gdcaac339 ./iso/master.yaml --image sgnos_alpine_amd64_k3s-master:latest --output sgnOS_alpine_amd64_k3s-master
      - uses: actions/upload-artifact@v2
        with:
          name: sgnOS_alpine_amd64_k3s-master.iso
          path: sgnOS_alpine_amd64_k3s-master.iso
          if-no-files-found: error

  build-amd64-agent:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build agent-amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.fedora
          platforms: linux/amd64
          push: false
          load: true
          tags: sgnos_amd64_k3s-agent:latest
          target: k3s-amd64
          build-args: |
            NODE=agent
      - name: Build agent amd64 iso
        run: docker run -v $PWD:/cOS -v /var/run:/var/run --entrypoint /usr/bin/luet-makeiso -i --rm quay.io/costoolkit/toolchain:0.8.7-16-gdcaac339 ./iso/master.yaml --image sgnos_amd64_k3s-agent:latest --output sgnOS_amd64_k3s-agent
      - uses: actions/upload-artifact@v2
        with:
          name: sgnOS_amd64_k3s-agent.iso
          path: sgnOS_amd64_k3s-agent.iso
          if-no-files-found: error

  build-arm64-master:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build master-aarch64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.fedora
          platforms: linux/arm64
          push: false
          load: true
          tags: sgnos_aarch64_k3s-master:latest
          target: base
          build-args: |
            NODE=master
      - name: Build Image
        id: build_image
        run: |
          sudo ./images/arm-img-builder.sh --model rpi64 --docker-image sgnos_aarch64_k3s-master:latest sgnOS_rpi64_k3s-master.img
      - uses: actions/upload-artifact@v2
        with:
          name: sgnOS_rpi64_k3s-master.img
          path: sgnOS_rpi64_k3s-master.img
          if-no-files-found: error

  build-arm64-agent:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build agent-aarch64 🔧
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.fedora
          platforms: linux/arm64
          push: false
          load: true
          tags: sgnos_aarch64_k3s-agent:latest
          target: base
          build-args: |
            NODE=agent
      - name: Build Image
        id: build_image
        run: |
          mkdir build
          sudo ./images/arm-img-builder.sh --model rpi64 --docker-image sgnos_aarch64_k3s-agent:latest sgnOS_rpi64_k3s-agent.img
      - uses: actions/upload-artifact@v2
        with:
          name: sgnOS_rpi64_k3s-agent.img
          path: sgnOS_rpi64_k3s-agent.img
          if-no-files-found: error

  build-ubuntu-arm64-master:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build master-aarch64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ubuntu
          platforms: linux/arm64
          push: false
          load: true
          tags: sgnos_ubuntu-aarch64_k3s-master:latest
          target: base
          build-args: |
            NODE=master
      - name: Build Image
        id: build_image
        run: |
          sudo ./images/arm-img-builder.sh --model rpi64 --docker-image sgnos_ubuntu-aarch64_k3s-master:latest sgnOS_ubuntu_rpi64_k3s-master.img
      - uses: actions/upload-artifact@v2
        with:
          name: sgnOS_ubuntu_rpi64_k3s-master.img
          path: sgnOS_ubuktu_rpi64_k3s-master.img
          if-no-files-found: error
