name: Release sgnOS image

on:
  create:
    tags:
      - v*

jobs:
  release-iso:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - name: Release space from worker
        run: |
          sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
      - name: Build  🔧
        run: docker build -t sgnos:${GITHUB_REF##*/} . 
      - name: Build iso
        run: |
          docker run -v $PWD:/cOS -v /var/run:/var/run --entrypoint /usr/bin/luet-makeiso --rm quay.io/costoolkit/toolchain ./iso.yaml --image sgnos:${GITHUB_REF##*/}
          mv *.iso build/
          mv *.sha256 build/
      - name: upload iso
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
